### ISSUE TITLE
useful prefix list

### ISSUE THREAD

**Issue by erxson** [ZQiu233/QTRHacker#23]
original is on russian, because im ruski kurwo, so I tried to translate on english

None=0
Weapon=0
Godly=59
Legendary=81
Unreal=82
Demonic=60
Mythical=83
Mystic=26
Acc's=0
Def=65
Mana=66
Crit=68
Damage=72

**Comment by Qiu233** [comment]
Good job. But not so useful.
In the very early versions, this hack once had the full list of prefixes but it turns out to made the UI hard to use. Users were forced to search the huge unsorted list for the most frequently used ones. Terraria uses a byte to hold prefix data, which means there're up to 255 types of prefix. It's not a good idea to give too many choices to users.
On the other hand, the editor of inventory as well as those of banks is a little incomplete, missing some important functions. But they're designed to be easy/quick to use, so it would be a good idea to make a new UI to hold item modifications in detail.

**Comment by erxson** [comment]
But these prefixes are the best in the game. For example, melee weapon - Godly/Legendary.

**Comment by Qiu233** [comment]
> But these prefixes are the best in the game. For example, melee weapon - Godly/Legendary.

Alright, got it, maybe later.

**Comment by erxson** [comment]
@Qiu233 check pull requests
