### ISSUE TITLE
Github actions?

### ISSUE THREAD

**Issue by erxson** [ZQiu233/QTRHacker#24]
I know that its possible with java repositories, what about c#?

**Comment by Qiu233** [comment]
Sorry, but I'm not sure what your question is.
I'm not a Java developer. This hack is mostly written in C#, except for QHackCLR the library designed to fetch CLR information using DAC. It's written in C++/CLI.
I've never learn about Github Actions.
Can you give more information about what this issue is for?

**Comment by erxson** [comment]
Just auto compile

**Comment by Qiu233** [comment]
Got it. I think it's also possible for C# but seems a little complicated. Maybe later.

**Comment by erxson** [comment]
https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
https://docs.microsoft.com/en-us/dotnet/devops/create-dotnet-github-action
https://docs.microsoft.com/en-us/dotnet/architecture/devops-for-aspnet-developers/actions-build
